### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jacmoe** [netpipe/sdl2-console#1]
Hello,

I am wondering if you could perhaps add a license?

Preferably a permissive one, like MIT or ZLIB or BSD.

I am looking for in game SDL2 based consoles, and your project seems to be a very nice starting point for my project :)

Thanks in advance!

**Comment by netpipe** [comment]
Raknarg on http://compsci.ca/v3/viewtopic.php?t=39585   was the original author i only ported it to sdl 1.2 all my changes would be permissive use.

**Comment by jacmoe** [comment]
Thanks for pointing me to the original. I guess the Unlicense (public domain) would be an appropriate license, then. :)
But since you took the code, improved and published it, you have the right to relicense it as you please. Especially considering that libtmt is under a BSD-style license.
Thanks again!
